mode: development
media_root: media
media_url: /media
base_url: /
plugins:
  - hyde.ext.plugins.meta.MetaPlugin
  - hyde.ext.plugins.git.GitDatesPlugin
  - hyde.ext.plugins.combine.CombinePlugin
  - hyde.ext.plugins.languages.LanguagePlugin
  - hyde.ext.plugins.auto_extend.AutoExtendPlugin
  - hyde.ext.plugins.sorter.SorterPlugin
  - hyde.ext.plugins.tagger.TaggerPlugin
  - hyde.ext.plugins.less.LessCSSPlugin
  - hyde.ext.plugins.textlinks.TextlinksPlugin
  - extensions.images.ImageThumbnailsPlugin
context:
  data:
    base: http://andreas-h.info
    languages:
      de: Deutsch
      en: English
meta:
  nodemeta: meta.yaml
  author: Andreas Hilboll
  title: "Disruptive Ninja"
  created: git
  modified: git
  language: de
  analytics: UA-21482482-4
  disqus: luffycx
  keywords: "debian, python, network, vincent bernat"
#typekit: hen2cfo
googlefonts: PT+Serif|PT+Sans+Caption|Inconsolata
less:
  app: /home/andreas/.virtualenvs/hyde/bin/lessc
markdown:
  extensions:
    - codehilite
    - extra
    - toc
  output_format: html
sorter:
  name:
    attr:
      - relative_path
  time:
    attr:
      - meta.created
    reverse: true
    filters:
      source.kind: html
      meta.listable: true
  time_de:
    attr:
      - meta.created
      - relative_path
    reverse: true
    filters:
      source.kind: html
      meta.listable: true
      meta.language: de
  time_en:
    attr:
      - meta.created
      - relative_path
    reverse: true
    filters:
      source.kind: html
      meta.listable: true
      meta.language: en
tagger:
  sorter: time
  tags:
    "ssl":
      descr: "SSL/TLS"
    "network":
      descr_en: "Networking"
      descr_de: "Réseau"
