extends: base.j2
default_block: article

language: fr
menu:
  -
     name: "CV"
     page: "cv.html"
  -
     name: "Projets"
     page: "projets.html"
  -
     name: "Blog"
     page: "blog/"
l10n:
  search: "Rechercher"
  otherlinks: "Autres liens"
  translations: "Autres langues"
  posts: "Autres articles"
  next: "Suivant"
  previous: "Précédent"
  comments: "Voir les commentaires ou en laisser un (avec Disqus)"
  attachments: "Documents liés"
  tags: "Étiquettes"
