extends: base.j2
default_block: article

language: de
menu:
  -
     name: "Über mich"
     page: "about.html"
  -
     name: "Forschung"
     page: "forschung.html"
  -
     name: "Techlog"
     page: "techlog/"
  -
     name: "Links"
     page: "links.html"
l10n:
  attachments: "Anhänge"
  by: "durch"
  comments: "Kommentare (mit Disqus)"
  imprint: "impressum"
  next: "Weiter"
  otherlinks: "Weitere Links"
  Page: "Diese Seite"
  posts: "Weitere Artikel"
  Powered: "Erzeugt"
  previous: "Zurück"
  search: "Suche"
  Site: "Ganze Webpräsenz"
  sources: "Quellen"
  tags: "Tags"
  translations: "Weitere Sprachen"

